# Generated by Django 2.0.5 on 2019-06-15 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Loja')),
                ('initials', models.CharField(max_length=100, verbose_name='Sigla da Loja')),
                ('url', models.CharField(max_length=100, verbose_name='URL da Loja')),
                ('client_id_mp', models.CharField(max_length=255, verbose_name='CLIENT_ID (Mercado Pago)')),
                ('client_secret_mp', models.CharField(max_length=255, verbose_name='CLIENT_SECRET (Mercado Pago)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('status', models.BooleanField(choices=[(1, 'Pessoa Física'), (2, 'Pessoa Jurídica')], default=True, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Lojas',
            },
        ),
    ]
