# Generated by Django 2.0.5 on 2019-06-16 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('slug', models.SlugField(max_length=40, verbose_name='Apelido')),
                ('link', models.CharField(max_length=255, verbose_name='Link para o Produto')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Custo do Produto')),
                ('markup', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Markup')),
                ('recommended_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço recomendado')),
                ('price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Preço Final')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('status', models.BooleanField(choices=[(1, 'Ativa'), (2, 'Inativa')], default=True, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('local', models.CharField(max_length=100, verbose_name='Localização')),
                ('link', models.CharField(max_length=255, verbose_name='Link da Loja')),
                ('whatsapp', models.CharField(max_length=255, verbose_name='Número de Whatsapp')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('status', models.BooleanField(choices=[(1, 'Ativa'), (2, 'Inativa')], default=True, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provarme_dashboard.Provider'),
        ),
    ]
