# Generated by Django 2.0.5 on 2018-06-28 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0002_auto_20180628_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Descrição'),
        ),
    ]
