# Generated by Django 2.0.5 on 2019-06-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0002_auto_20190616_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativa'), (False, 'Inativa')], default=True, verbose_name='Situação'),
        ),
    ]
