# Generated by Django 2.0.5 on 2019-06-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0003_auto_20190616_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='marketing',
            field=models.IntegerField(default=20, verbose_name='Custo com Marketing'),
        ),
    ]
