# Generated by Django 2.0.5 on 2018-06-28 19:56

from django.db import migrations, models
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0003_auto_20180628_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wording', models.TextField(verbose_name='Enunciado')),
                ('hint', models.TextField(blank=True, verbose_name='Dica')),
                ('comment', models.TextField(blank=True, verbose_name='Comentário')),
                ('active', models.BooleanField(default=True, verbose_name='Situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('categories', mptt.fields.TreeManyToManyField(to='provarme_dashboard.Category', verbose_name='Categoria')),
            ],
        ),
    ]
