# Generated by Django 2.0.5 on 2018-07-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0004_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='order',
        ),
    ]
