# Generated by Django 2.0.5 on 2019-06-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0004_product_marketing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='Telefone (Whatsapp)')),
                ('number_order', models.CharField(max_length=255, verbose_name='Número do Pedido')),
                ('code_tracking', models.CharField(max_length=255, verbose_name='Código de Rastreio')),
                ('type_purchase', models.CharField(choices=[('via Cartão de Crédito', 'via Cartão de Crédito'), ('via Boleto Bancário', 'via Boleto Bancário')], max_length=255, verbose_name='Tipo de Compra')),
                ('address', models.CharField(max_length=255, verbose_name='Endereço')),
                ('zipcode', models.CharField(max_length=255, verbose_name='CEP')),
                ('city', models.CharField(max_length=255, verbose_name='Cidade')),
                ('state', models.CharField(max_length=255, verbose_name='Estado (UF)')),
                ('reason', models.CharField(max_length=255, verbose_name='Motivo da devolução')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provarme_dashboard.Product')),
            ],
            options={
                'verbose_name': 'Trocas e Devoluções',
                'verbose_name_plural': 'Trocas e Devoluções',
            },
        ),
        migrations.CreateModel(
            name='Traffic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_shopify', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Taxa Shopify')),
                ('tx_gateway', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Taxa do Gateway')),
                ('tx_antecipation', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Taxa de Antecipação')),
                ('tx_tax', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Imposto')),
                ('tx_iof', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='IOF')),
                ('tx_cashback', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Cashback')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modificado em')),
                ('status', models.BooleanField(choices=[(1, 'Ativa'), (2, 'Inativa')], default=True, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Tráfego',
            },
        ),
    ]
