# Generated by Django 2.0.5 on 2019-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0006_auto_20190623_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=40, unique=True, verbose_name='Descrição')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('type_categories', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('T', 'Todos')], default='S', max_length=1, verbose_name='tipo')),
            ],
            options={
                'ordering': ['description'],
            },
        ),
    ]
