# Generated by Django 2.0.5 on 2019-06-25 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0008_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nome')),
                ('maturity', models.DateTimeField(blank=True, null=True, verbose_name='Data')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('emission_date', models.DateTimeField(blank=True, null=True, verbose_name='Data de Emissão')),
                ('settle', models.BooleanField(choices=[('Pago', True), ('Não Pago', False)], default=False, verbose_name='Liquidar')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'ordering': ['maturity', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='expense',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provarme_dashboard.Account'),
        ),
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provarme_dashboard.Category'),
        ),
    ]
