# Generated by Django 2.0.5 on 2019-06-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0009_order'),
        ('provarme_dashboard', '0010_auto_20190625_2058'),
    ]

    operations = [
    ]
