# Generated by Django 2.0.5 on 2019-06-28 04:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0011_merge_20190626_1024'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'verbose_name': 'Pedido', 'verbose_name_plural': 'Pedidos'},
        ),
        migrations.AlterModelOptions(
            name='setup',
            options={'verbose_name': 'Configuração', 'verbose_name_plural': 'Configurações'},
        ),
        migrations.AlterModelOptions(
            name='traffic',
            options={'verbose_name': 'Tráfego diário', 'verbose_name_plural': 'Tráfego'},
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='status',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='tx_antecipation',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='tx_cashback',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='tx_gateway',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='tx_iof',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='tx_shopify',
        ),
        migrations.RemoveField(
            model_name='traffic',
            name='tx_tax',
        ),
        migrations.AddField(
            model_name='traffic',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Data'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traffic',
            name='investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Investimento (R$)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traffic',
            name='order_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Número de Pedidos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='traffic',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='traffic', to='provarme_dashboard.Product', verbose_name='Produto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='ativa'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='setup',
            name='status',
            field=models.BooleanField(choices=[(True, 'Ativo'), (False, 'Inativo')], default=True, verbose_name='Situação'),
        ),
    ]
