# Generated by Django 2.0.5 on 2019-06-28 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0012_auto_20190628_0149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='traffic',
            options={'ordering': ['-event_date'], 'verbose_name': 'Tráfego diário', 'verbose_name_plural': 'Tráfego'},
        ),
    ]
