# Generated by Django 2.0.5 on 2019-06-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0013_auto_20190628_0201'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='traffic',
            unique_together={('product', 'event_date')},
        ),
    ]
