# Generated by Django 2.0.5 on 2019-06-28 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0014_auto_20190628_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traffic',
            name='investment',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Investimento (R$)'),
        ),
    ]
