# Generated by Django 2.0.5 on 2019-06-28 07:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0015_auto_20190628_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='category',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='customer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='devolution',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devolution',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='devolution',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AddField(
            model_name='expense',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='order',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='provider',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='setup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AddField(
            model_name='traffic',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
    ]
