# Generated by Django 2.0.5 on 2019-06-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0016_auto_20190628_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='emission_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Emissão'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='maturity',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
    ]
