# Generated by Django 2.0.5 on 2019-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0017_auto_20190628_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
    ]
