# Generated by Django 2.0.5 on 2019-06-29 01:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0019_checkout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkout',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkouts', to='provarme_dashboard.Customer'),
        ),
    ]
