# Generated by Django 2.0.5 on 2019-06-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_dashboard', '0020_auto_20190628_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkout',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Status'),
        ),
    ]
