# Generated by Django 2.0.5 on 2018-07-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Aluno', 'verbose_name_plural': 'Alunos'},
        ),
    ]
