# Generated by Django 2.0.5 on 2018-07-05 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Professor', 'verbose_name_plural': 'Professores'},
        ),
    ]
