# Generated by Django 2.0.5 on 2019-06-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20190628_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='url',
            field=models.URLField(max_length=100, verbose_name='URL da Loja'),
        ),
    ]
