# Generated by Django 2.0.5 on 2019-06-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20190628_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Excluido em'),
        ),
    ]
