# Generated by Django 2.0.5 on 2019-06-28 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_store_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='initials',
        ),
    ]
