# Generated by Django 2.0.5 on 2019-06-19 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import provarme_tenant.models
import tenant_schemas.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_url', models.CharField(max_length=128, unique=True)),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[tenant_schemas.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('name_fantasy', models.CharField(max_length=500, verbose_name='Nome de Fantasia')),
                ('document', models.CharField(blank=True, max_length=20, null=True, verbose_name='CNPJ ou CPF')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Número de Telefone')),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True, verbose_name='CEP')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade')),
                ('province', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado/Província')),
                ('address', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Endereço')),
                ('address_number', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Número')),
                ('neighborhood', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Bairro')),
                ('acceptance', models.BooleanField(default=False, verbose_name='Aceito os termos')),
                ('is_active', models.BooleanField(default=False, verbose_name='Ativo?')),
                ('display_site', models.BooleanField(default=False)),
                ('display_landing', models.BooleanField(default=False)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Nome')),
                ('description', models.CharField(max_length=500, verbose_name='Descrição')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Preço')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('created_on', models.DateField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Plano',
                'verbose_name_plural': 'Planos',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cellphone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=40)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=provarme_tenant.models.Profile.image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_product', models.IntegerField(null=True, verbose_name='ID do produto')),
                ('purchase_date', models.DateField(auto_now_add=True, null=True, verbose_name='Data da Compra')),
                ('prod_name', models.CharField(max_length=255, null=True, verbose_name='Nome do produto')),
                ('transaction', models.IntegerField(default=0, null=True, verbose_name='ID da da venda')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email do Comprador')),
                ('first_name', models.CharField(max_length=100, null=True, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=100, null=True, verbose_name='Último Nome')),
                ('cpf', models.CharField(max_length=11, null=True, verbose_name='CPF')),
                ('phone_local_code', models.CharField(max_length=3, null=True, verbose_name='DDD')),
                ('phone_number', models.CharField(max_length=9, null=True, verbose_name='Telefone')),
                ('payment_type', models.CharField(max_length=100, null=True, verbose_name='Tipo')),
                ('status', models.CharField(max_length=100, null=True, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
