# Generated by Django 2.0.5 on 2018-06-21 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 21, 19, 40, 23, 18921), verbose_name='Valido até'),
        ),
    ]
