# Generated by Django 2.0.5 on 2019-06-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-purchase_date'], 'verbose_name': 'Compra', 'verbose_name_plural': 'Compras'},
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='active_url',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='client',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='modified_on',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='validate_on',
        ),
        migrations.AddField(
            model_name='purchase',
            name='cod_product',
            field=models.IntegerField(null=True, verbose_name='ID do produto'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='cpf',
            field=models.CharField(max_length=11, null=True, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='email',
            field=models.CharField(max_length=255, null=True, verbose_name='Email do Comprador'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='first_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Primeiro Nome'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='last_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Último Nome'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='payment_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Tipo'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone_local_code',
            field=models.CharField(max_length=3, null=True, verbose_name='DDD'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='phone_number',
            field=models.CharField(max_length=9, null=True, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='prod_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Nome do produto'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Data da Compra'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='transaction',
            field=models.IntegerField(default=0, null=True, verbose_name='ID da da venda'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.CharField(max_length=100, null=True, verbose_name='Situação'),
        ),
    ]
