# Generated by Django 2.0.5 on 2018-06-26 13:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0002_auto_20180621_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 13, 0, 49, 387778), verbose_name='Valido até'),
        ),
    ]
