# Generated by Django 2.0.5 on 2018-06-26 14:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0003_auto_20180626_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 26, 14, 38, 22, 398304), verbose_name='Valido até'),
        ),
    ]
