# Generated by Django 2.0.5 on 2018-06-28 16:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0005_auto_20180628_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 16, 7, 36, 780355), verbose_name='Valido até'),
        ),
    ]
