# Generated by Django 2.0.5 on 2018-06-28 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0007_auto_20180628_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 28, 16, 11, 27, 410483), verbose_name='Valido até'),
        ),
    ]
