# Generated by Django 2.0.5 on 2019-06-13 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0011_auto_20180705_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 13, 18, 45, 23, 584329), verbose_name='Valido até'),
        ),
    ]
