# Generated by Django 2.0.5 on 2019-06-15 15:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0012_auto_20190613_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 15, 30, 14, 678600), verbose_name='Valido até'),
        ),
    ]
