# Generated by Django 2.0.5 on 2019-06-15 17:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0013_auto_20190615_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 15, 17, 31, 45, 900176), verbose_name='Valido até'),
        ),
    ]
