# Generated by Django 2.0.5 on 2019-06-16 11:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0014_auto_20190615_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 11, 44, 7, 108767), verbose_name='Valido até'),
        ),
    ]
