# Generated by Django 2.0.5 on 2019-06-16 12:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0015_auto_20190616_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 12, 40, 33, 816450), verbose_name='Valido até'),
        ),
    ]
