# Generated by Django 2.0.5 on 2019-06-16 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0019_auto_20190616_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 16, 13, 11, 18, 492140), verbose_name='Valido até'),
        ),
    ]
