# Generated by Django 2.0.5 on 2019-06-19 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provarme_tenant', '0021_auto_20190616_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 7, 19, 10, 4, 23, 710289), verbose_name='Valido até'),
        ),
    ]
