# Generated by Django 2.0.5 on 2018-05-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='name_fantasy',
            field=models.CharField(default='Empresa Padrão', max_length=500),
            preserve_default=False,
        ),
    ]
