# Generated by Django 2.0.5 on 2018-05-27 14:33

import atrix_tenant.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atrix_tenant', '0004_client_display_landing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cellphone', models.CharField(max_length=20)),
                ('cnpj', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=40)),
                ('image_profile', models.ImageField(blank=True, null=True, upload_to=atrix_tenant.models.Profile.image_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
