# Generated by Django 2.0.5 on 2018-06-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0008_auto_20180607_1040'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='user',
        ),
        migrations.AddField(
            model_name='purchase',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='atrix_tenant.Client', verbose_name='Inquilino'),
            preserve_default=False,
        ),
    ]
