# Generated by Django 2.0.5 on 2018-06-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0009_auto_20180607_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='active_url',
            field=models.CharField(default=1, max_length=500, verbose_name='URL de ativação'),
            preserve_default=False,
        ),
    ]
