# Generated by Django 2.0.5 on 2018-06-07 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0010_purchase_active_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='modified_on',
            field=models.DateTimeField(auto_now=True, verbose_name='Modificado em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='plan',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo?'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='created_on',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
