# Generated by Django 2.0.5 on 2018-06-07 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0011_auto_20180607_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Pendente'), (1, 'Pago'), (2, 'Cancelado')], default=0, verbose_name='Situação'),
        ),
    ]
