# Generated by Django 2.0.5 on 2018-06-07 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0012_auto_20180607_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atrix_tenant.Plan', verbose_name='Plano contratado'),
        ),
    ]
