# Generated by Django 2.0.5 on 2018-06-07 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0013_auto_20180607_2153'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='plan',
        ),
    ]
