# Generated by Django 2.0.5 on 2018-06-08 01:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0015_purchase_validate_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='pagseguro_redirect_url',
        ),
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 1, 2, 40, 673316), verbose_name='Valido até'),
        ),
    ]
