# Generated by Django 2.0.5 on 2018-06-08 15:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0016_auto_20180608_0102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 8, 15, 24, 23, 682991), verbose_name='Valido até'),
        ),
    ]
