# Generated by Django 2.0.5 on 2018-06-18 10:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0017_auto_20180608_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 10, 9, 12, 130686), verbose_name='Valido até'),
        ),
    ]
