# Generated by Django 2.0.5 on 2018-06-18 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0018_auto_20180618_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 18, 32, 27, 941264), verbose_name='Valido até'),
        ),
    ]
