# Generated by Django 2.0.5 on 2018-06-18 18:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0019_auto_20180618_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 18, 18, 50, 14, 555633), verbose_name='Valido até'),
        ),
    ]
