# Generated by Django 2.0.5 on 2018-06-19 20:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0020_auto_20180618_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 19, 20, 1, 5, 557031), verbose_name='Valido até'),
        ),
    ]
