# Generated by Django 2.0.5 on 2018-06-20 00:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atrix_tenant', '0021_auto_20180619_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='validate_on',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 20, 0, 21, 0, 711141), verbose_name='Valido até'),
        ),
    ]
